name: flutter_cal
description: A new Flutter project.
publish_to: 'none' # Remove this line to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^2.12.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dough: ^1.0.1
  hooks_riverpod: ^0.14.0+3
  flutter_hooks: ^0.16.0
  functional_widget: ^0.9.0+1
  flutter_neumorphic: ^3.1.0
  

dev_dependencies:
  functional_widget_annotation: ^0.9.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.2
  code_builder: ^4.0.0

flutter:
  uses-material-design: true

